import { useState } from 'react';
import Head from 'next/head';
import Game from '../components/Game';
import Link from 'next/link';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="fixed w-screen">
        <main className="flex justify-center items-center h-screen max-h-full overflow-hidden relative -mt-24">
          <div>
            <p className="text-sm md:text-2xl p-4 text-center">
              Pick a operator
            </p>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-3 md:gap-8">
              {[
                { symbol: '+', name: 'add' },
                { symbol: '-', name: 'subtract' },
                { symbol: '×', name: 'multiply' },
                { symbol: '÷', name: 'divide' },
              ].map((operator) => (
                <Link
                  href={`/${operator.name}`}
                  className={`border rounded text-md md:text-5xl p-4 text-center`}
                  key={operator.name}>
                  {operator.symbol}
                </Link>
              ))}
            </div>
          </div>
        </main>
      </div>
    </div>
  );
}
